name: Deploy Supabase Edge Functions

# Este robô roda toda vez que você envia código para a branch 'main'
on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**' # Só roda se houver mudanças nas funções

jobs:
  deploy-function:
    runs-on: ubuntu-latest # Usa uma máquina virtual Linux
    steps:
      - name: Check out repository
        uses: actions/checkout@v3 # Baixa o código do seu repositório

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1 # Instala a ferramenta de linha de comando do Supabase
        with:
          version: latest
#dsa
      - name: Deploy Edge Function
        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}